"""phase2 intelligence: strategies, market_regimes, signals, opportunity_scores

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-15 20:04:52.616252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('family', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('lifecycle_stage', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("lifecycle_stage IN ('idea','backtest','out_of_sample','paper','small_capital','production','quarantine','retired')", name='ck_strategies_lifecycle_stage'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.CheckConstraint("regime IN ('trending_bull','trending_bear','ranging','high_volatility','low_volatility','panic','euphoria','transition','unknown')", name='ck_market_regimes_regime'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_price', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('regime_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("direction IN ('long','short')", name='ck_signals_direction'),
    sa.CheckConstraint("status IN ('pending','scored','risk_rejected','approved','executed','expired')", name='ck_signals_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['regime_id'], ['market_regimes.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunity_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('technical', sa.Float(), nullable=False),
    sa.Column('pattern', sa.Float(), nullable=False),
    sa.Column('regime_fit', sa.Float(), nullable=False),
    sa.Column('historical_edge', sa.Float(), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=False),
    sa.Column('news', sa.Float(), nullable=False),
    sa.Column('risk_reward', sa.Float(), nullable=False),
    sa.Column('strategy_performance', sa.Float(), nullable=False),
    sa.Column('volatility_penalty', sa.Float(), nullable=False),
    sa.Column('correlation_penalty', sa.Float(), nullable=False),
    sa.Column('execution_cost_penalty', sa.Float(), nullable=False),
    sa.Column('drawdown_penalty', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("tier IN ('ignore','watch','possible','high_quality','exceptional')", name='ck_opportunity_scores_tier'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', name='uq_opportunity_scores_signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunity_scores')
    op.drop_table('signals')
    op.drop_table('market_regimes')
    op.drop_table('strategies')
    # ### end Alembic commands ###
