"""phase3 risk and execution: risk_checks, risk_decisions, positions, orders, trades, correlation_matrix

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-15 20:45:39.316472

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation_matrix',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id_a', sa.Integer(), nullable=False),
    sa.Column('asset_id_b', sa.Integer(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id_a'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['asset_id_b'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('ts', 'asset_id_a', 'asset_id_b', 'window_days')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('current_stop', sa.Float(), nullable=False),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(), nullable=True),
    sa.CheckConstraint("direction IN ('long','short')", name='ck_positions_direction'),
    sa.CheckConstraint("status IN ('open','closed')", name='ck_positions_status'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_size', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('safety_belt_level', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', name='uq_risk_decisions_signal_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('slippage_bps', sa.Float(), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.CheckConstraint("order_type IN ('market','limit','stop')", name='ck_orders_order_type'),
    sa.CheckConstraint("side IN ('buy','sell')", name='ck_orders_side'),
    sa.CheckConstraint("status IN ('new','submitted','filled','partially_filled','cancelled','rejected')", name='ck_orders_status'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('opened_order_id', sa.Integer(), nullable=True),
    sa.Column('closed_order_id', sa.Integer(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("outcome IN ('win','loss','breakeven')", name='ck_trades_outcome'),
    sa.ForeignKeyConstraint(['closed_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['opened_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trades')
    op.drop_table('orders')
    op.drop_table('risk_decisions')
    op.drop_table('risk_checks')
    op.drop_table('positions')
    op.drop_table('correlation_matrix')
    # ### end Alembic commands ###
