"""phase4 news, patterns, pattern performance

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-15 21:55:19.321147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('raw_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('central_bank','inflation','employment','gdp','geopolitics','regulation','crypto','earnings','m_and_a','other')", name='ck_news_events_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pattern_performance',
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('regime', sa.String(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_r_multiple', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pattern_type', 'regime')
    )
    op.create_table('news_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_event_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('horizon_hours', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("direction IN ('bullish','bearish','neutral')", name='ck_news_impact_direction'),
    sa.CheckConstraint("impact IN ('low','medium','high')", name='ck_news_impact_impact'),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_news_impact_confidence'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['news_event_id'], ['news_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('pattern_class', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.CheckConstraint("direction IN ('bullish','bearish','neutral')", name='ck_patterns_direction'),
    sa.CheckConstraint("pattern_class IN ('technical','statistical','cross_market')", name='ck_patterns_pattern_class'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('signals', sa.Column('pattern_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'signals', 'patterns', ['pattern_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signals', type_='foreignkey')
    op.drop_column('signals', 'pattern_id')
    op.drop_table('patterns')
    op.drop_table('news_impact')
    op.drop_table('pattern_performance')
    op.drop_table('news_events')
    # ### end Alembic commands ###
