"""phase6 backtesting: backtest_runs

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-15 22:53:36.336338

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('group_label', sa.String(), nullable=True),
    sa.Column('window_index', sa.Integer(), nullable=True),
    sa.Column('total_windows', sa.Integer(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('net_return', sa.Float(), nullable=True),
    sa.Column('cagr_like_return', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('avg_trade', sa.Float(), nullable=True),
    sa.Column('expectancy', sa.Float(), nullable=True),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.Column('sharpe_like', sa.Float(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('backtest','out_of_sample','walk_forward_window','stability_check')", name='ck_backtest_runs_kind'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
