"""prompt2 market data engine: market_events table, alerts market category

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-18 21:10:10.286979

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint(
        "event_type IN ('PRICE_MOVEMENT','VOLUME_SPIKE','VOLATILITY_SPIKE','BREAKOUT_CANDIDATE',"
        "'MOMENTUM_CHANGE','TREND_CHANGE','ANOMALY','INVALID_MARKET_DATA')",
        name='ck_market_events_event_type',
    ),
    sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH','CRITICAL')", name='ck_market_events_severity'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_events_asset_id'), 'market_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_market_events_event_type'), 'market_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_market_events_ts'), 'market_events', ['ts'], unique=False)
    # ### end Alembic commands ###

    # Autogenerate doesn't diff CHECK constraint bodies, so this is hand-written:
    # widen alerts.category to allow 'market' (data feed disconnected, stale
    # data, unusual movement, volatility spike, high-severity market events --
    # apps/worker/scanner.py) alongside the existing categories.
    op.drop_constraint('ck_alerts_category', 'alerts', type_='check')
    op.create_check_constraint(
        'ck_alerts_category',
        'alerts',
        "category IN ('trade','risk','loss','emergency','learning','system','market')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_alerts_category', 'alerts', type_='check')
    op.create_check_constraint(
        'ck_alerts_category',
        'alerts',
        "category IN ('trade','risk','loss','emergency','learning','system')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_events_ts'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_event_type'), table_name='market_events')
    op.drop_index(op.f('ix_market_events_asset_id'), table_name='market_events')
    op.drop_table('market_events')
    # ### end Alembic commands ###
