"""prompt7_backtest_lab

Revision ID: 0012
Revises: 0011
Create Date: 2026-08-19 11:49:00.059228

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('backtest','walk_forward','walk_forward_optimization','optimize','monte_carlo','stress_test','sensitivity','full_lab')", name='ck_backtest_jobs_kind'),
    sa.CheckConstraint("status IN ('queued','running','completed','failed','cancelled')", name='ck_backtest_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monte_carlo_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('num_simulations', sa.Integer(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('percentiles', sa.JSON(), nullable=False),
    sa.Column('probability_of_loss', sa.Float(), nullable=True),
    sa.Column('probability_of_drawdown_threshold', sa.Float(), nullable=True),
    sa.Column('drawdown_threshold_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("method IN ('trade_reshuffling','bootstrap','return_perturbation','slippage_perturbation','execution_perturbation')", name='ck_monte_carlo_runs_method'),
    sa.ForeignKeyConstraint(['reference_backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stress_test_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('scenario', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('survived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reference_backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('system_state', sa.Column('backtest_worker_last_heartbeat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('backtest_runs', sa.Column('strategy_version', sa.String(), nullable=True))
    op.add_column('backtest_runs', sa.Column('code_version', sa.String(), nullable=True))
    op.add_column('backtest_runs', sa.Column('data_version', sa.String(), nullable=True))
    op.add_column('backtest_runs', sa.Column('random_seed', sa.Integer(), nullable=True))
    # extra_metrics is new and NOT NULL on an already-populated table -- backfill
    # existing rows with an honest empty bundle (no metric was ever computed for
    # them under the old schema, so '{}' is the truthful value, not a guess),
    # then drop the server_default so future inserts must supply it explicitly.
    op.add_column('backtest_runs', sa.Column('extra_metrics', sa.JSON(), nullable=False, server_default='{}'))
    op.alter_column('backtest_runs', 'extra_metrics', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('backtest_runs', 'extra_metrics')
    op.drop_column('backtest_runs', 'random_seed')
    op.drop_column('backtest_runs', 'data_version')
    op.drop_column('backtest_runs', 'code_version')
    op.drop_column('backtest_runs', 'strategy_version')
    op.drop_column('system_state', 'backtest_worker_last_heartbeat')
    op.drop_table('stress_test_runs')
    op.drop_table('monte_carlo_runs')
    op.drop_table('backtest_jobs')
    # ### end Alembic commands ###
