"""prompt8_autonomous_trading

Revision ID: 0013
Revises: 0012
Create Date: 2026-08-19 14:00:00.000000

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0013'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.CheckConstraint(
        "event_type IN ('order_submitted','order_filled','order_rejected',"
        "'position_opened','position_closed','risk_blocked','no_trade',"
        "'trading_paused','trading_resumed','kill_switch_triggered',"
        "'kill_switch_released','reconciliation_mismatch',"
        "'portfolio_emergency_action','loss_streak_detected',"
        "'worker_restarted','crash_loop_protection_triggered')",
        name='ck_trading_events_event_type',
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trading_events_ts', 'trading_events', ['ts'])
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('autonomous_status', sa.String(), nullable=False),
    sa.Column('trading_mode', sa.String(), nullable=False),
    sa.Column('trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('trading_paused', sa.Boolean(), nullable=False),
    sa.Column('safety_belt_level', sa.String(), nullable=False),
    sa.Column('worker_alive', sa.Boolean(), nullable=False),
    sa.Column('open_positions_count', sa.Integer(), nullable=False),
    sa.Column('cadence_failures', sa.JSON(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.CheckConstraint(
        "autonomous_status IN ('starting','running','paused','no_trade',"
        "'caution','defensive','emergency','kill_switch','error')",
        name='ck_system_health_autonomous_status',
    ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.CheckConstraint(
        "action IN ('pause','resume','close_position','cancel_order',"
        "'kill_switch','kill_switch_release','reset_paper_account')",
        name='ck_manual_actions_action',
    ),
    sa.PrimaryKeyConstraint('id')
    )

    # system_state: TradingMode, PAUSE/RESUME, crash-loop protection.
    op.add_column('system_state', sa.Column('trading_mode', sa.String(), nullable=False, server_default='paper'))
    op.alter_column('system_state', 'trading_mode', server_default=None)
    op.create_check_constraint('ck_system_state_trading_mode', 'system_state', "trading_mode IN ('paper','live_disabled')")
    op.add_column('system_state', sa.Column('trading_paused', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('system_state', 'trading_paused', server_default=None)
    op.add_column('system_state', sa.Column('paused_reason', sa.Text(), nullable=True))
    op.add_column('system_state', sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('system_state', sa.Column('worker_restart_count', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('system_state', 'worker_restart_count', server_default=None)
    op.add_column('system_state', sa.Column('restart_window_started_at', sa.DateTime(timezone=True), nullable=True))

    # positions: trailing stops + a closed exit_reason vocabulary.
    op.add_column('positions', sa.Column('trailing_stop_config', sa.JSON(), nullable=True))
    op.add_column('positions', sa.Column('favorable_extreme_price', sa.Float(), nullable=True))
    op.create_check_constraint(
        'ck_positions_exit_reason', 'positions',
        "exit_reason IS NULL OR exit_reason IN ('stop_hit','target_hit','trailing_stop_hit',"
        "'thesis_invalidated','manual_close','kill_switch_close','portfolio_emergency_close',"
        "'reconciliation_pause','regime_change_exit')",
    )

    # orders: idempotency + execution quality.
    op.add_column('orders', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint('uq_orders_idempotency_key', 'orders', ['idempotency_key'])
    op.add_column('orders', sa.Column('expected_price', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('latency_ms', sa.Float(), nullable=True))

    # admin_users: RBAC role.
    op.add_column('admin_users', sa.Column('role', sa.String(), nullable=False, server_default='admin'))
    op.alter_column('admin_users', 'role', server_default=None)
    op.create_check_constraint('ck_admin_users_role', 'admin_users', "role IN ('admin','viewer')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_admin_users_role', 'admin_users', type_='check')
    op.drop_column('admin_users', 'role')

    op.drop_column('orders', 'latency_ms')
    op.drop_column('orders', 'expected_price')
    op.drop_constraint('uq_orders_idempotency_key', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')

    op.drop_constraint('ck_positions_exit_reason', 'positions', type_='check')
    op.drop_column('positions', 'favorable_extreme_price')
    op.drop_column('positions', 'trailing_stop_config')

    op.drop_column('system_state', 'restart_window_started_at')
    op.drop_column('system_state', 'worker_restart_count')
    op.drop_column('system_state', 'paused_at')
    op.drop_column('system_state', 'paused_reason')
    op.drop_column('system_state', 'trading_paused')
    op.drop_constraint('ck_system_state_trading_mode', 'system_state', type_='check')
    op.drop_column('system_state', 'trading_mode')

    op.drop_table('manual_actions')
    op.drop_table('system_health')
    op.drop_index('ix_trading_events_ts', 'trading_events')
    op.drop_table('trading_events')
    # ### end Alembic commands ###
