import { LegalDocument } from "@/components/LegalDocument";

export default function TermsPage() {
  return (
    <LegalDocument title="Terms of Service" lastUpdated="[TBD — set on legal review]">
      <section>
        <h2>1. Who this agreement is with</h2>
        <p>
          INNER (&quot;INNER,&quot; &quot;we,&quot; &quot;us&quot;) is operated by{" "}
          <strong>[Company legal name — TBD]</strong>, registered at <strong>[registered address — TBD]</strong>. By
          using inner&apos;s website or purchasing a report, you agree to these Terms and to our{" "}
          <a href="/privacy-policy" className="underline">
            Privacy Policy
          </a>
          .
        </p>
      </section>

      <section>
        <h2>2. What INNER is — and isn&apos;t</h2>
        <p>
          INNER offers short, adaptive self-reflection assessments that generate a personalized written report about
          patterns in how you relate to others. The assessments and reports are for entertainment and personal
          insight only.
        </p>
        <p>
          <strong>
            INNER is not a medical, psychological, psychiatric, or therapeutic service, and nothing in a report is a
            diagnosis or professional advice of any kind.
          </strong>{" "}
          If you&apos;re looking for mental health support, please consult a qualified professional.
        </p>
      </section>

      <section>
        <h2>3. AI-generated content</h2>
        <p>
          Some questions and all report content are partly generated by an AI model based on your answers. We apply
          filters to keep this content non-diagnostic and on-topic, but AI output can occasionally be inaccurate,
          generic, or miss the mark for your specific situation. Reports are a reflective tool, not a factual
          statement about you.
        </p>
      </section>

      <section>
        <h2>4. Eligibility</h2>
        <p>
          <strong>[Minimum age — TBD.]</strong> You must meet the minimum age required in your jurisdiction to use
          INNER without a parent or guardian, and to enter into a paid purchase in your own name. We don&apos;t
          currently verify age beyond this requirement.
        </p>
      </section>

      <section>
        <h2>5. Accounts and sessions</h2>
        <p>
          You don&apos;t need to register an account to use INNER. We identify your progress through an assessment
          using an anonymous, cookie-based session, and associate an order with the email address you provide at
          checkout so we can deliver your report.
        </p>
      </section>

      <section>
        <h2>6. Purchases and payment</h2>
        <p>
          A report is a one-time digital purchase, priced in EUR and shown before you pay. Payment is processed by
          Stripe; we never receive or store your full card details. Your report is generated and made available (and
          emailed to you) once payment is confirmed.
        </p>
      </section>

      <section>
        <h2>7. Refunds and digital content withdrawal</h2>
        <p>
          <strong>[Refund policy — TBD, needs explicit legal sign-off.]</strong> Because a report is digital content
          delivered immediately on payment, consumer-law &quot;cooling-off&quot; withdrawal rights (e.g. under EU
          law) may not apply once generation begins, but this depends on how and whether we obtain your explicit
          consent and acknowledgment at checkout — which is not yet finalized. Until this section is completed,
          refund requests are handled at our discretion; contact us using the details in Section 12.
        </p>
      </section>

      <section>
        <h2>8. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use automated tools, scripts, or bots to complete assessments or scrape assessment content;</li>
          <li>Attempt to access another person&apos;s session, order, or report;</li>
          <li>Interfere with or attempt to bypass the site&apos;s security, rate limits, or payment flow;</li>
          <li>Resell, redistribute, or publicly republish report content obtained through the service.</li>
        </ul>
      </section>

      <section>
        <h2>9. Intellectual property</h2>
        <p>
          The INNER product — including question banks, scoring logic, design, and branding — belongs to us or our
          licensors. Your report is licensed to you for personal, non-commercial use.
        </p>
      </section>

      <section>
        <h2>10. Disclaimers and limitation of liability</h2>
        <p>
          <strong>[Placeholder boilerplate — needs legal review before launch.]</strong> The service and all report
          content are provided &quot;as is,&quot; without warranties of any kind, express or implied. To the maximum
          extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from
          your use of INNER. Nothing in these Terms limits liability that cannot be limited under applicable
          consumer-protection law.
        </p>
      </section>

      <section>
        <h2>11. Governing law</h2>
        <p>
          <strong>[Governing law and venue — TBD.]</strong>
        </p>
      </section>

      <section>
        <h2>12. Changes to these Terms</h2>
        <p>
          We may update these Terms as the product changes. Material changes will be reflected in the &quot;Last
          updated&quot; date above.
        </p>
      </section>

      <section>
        <h2>13. Contact</h2>
        <p>
          Questions about these Terms: <strong>[contact email — TBD]</strong>.
        </p>
      </section>
    </LegalDocument>
  );
}
